#ifndef NE_SEGMENTER_PARAMS_H_INCLUDED
#define NE_SEGMENTER_PARAMS_H_INCLUDED

#include <Core/NParameters.h>

#define NESP_HORIZONTAL_MARGIN        10001
#define NESP_VERTICAL_MARGIN          10002
#define NESP_UPPER_EYELID_MASK_VALUE  10011
#define NESP_SCLERA_MASK_VALUE        10012
#define NESP_LOWER_EYELID_MASK_VALUE  10013

#define NESP_QUALITY_THRESHOLD                     20001

#endif // !NE_SEGMENTER_PARAMS_H_INCLUDED
