#ifndef NTFI_PARAMS_H_INCLUDED
#define NTFI_PARAMS_H_INCLUDED

#include <Core/NParameters.h>

#define NTFIP_TOKEN_FACE_IMAGE_WIDTH       10001
#define NTFIP_USE_LIGHTNESS_NORMALIZATION  10002

#define NTFIP_QUALITY_THRESHOLD                20001
#define NTFIP_SHARPNESS_THRESHOLD              20002
#define NTFIP_BACKGROUND_UNIFORMITY_THRESHOLD  20003
#define NTFIP_GRAYSCALE_DENSITY_THRESHOLD      20004

#endif // !NTFI_PARAMS_H_INCLUDED
