#ifndef N_MATCHER_PARAMS_H_INCLUDED
#define N_MATCHER_PARAMS_H_INCLUDED

#include <Core/NParameters.h>

#ifdef N_CPP
extern "C"
{
#endif

#define NMP_MATCHING_THRESHOLD 100

#define NMP_FUSION_TYPE                  200
#define NMP_FACES_MATCHING_THRESHOLD     210
#define NMP_FACES_MATCHING_THRESHOLD_NEW 215
#define NMP_IRISES_MATCHING_THRESHOLD    220

#define NMP_FINGERS_MATCHER_BASE                3536
#define NMP_FINGERS_MAXIMAL_ROTATION            (NMP_FINGERS_MATCHER_BASE +  201)
#define NMP_FINGERS_MATCHING_SPEED              (NMP_FINGERS_MATCHER_BASE +  220)
#define NMP_FINGERS_FILL_FULL_MATCHING_DETAILS  (NMP_FINGERS_MATCHER_BASE +  900)
#define NMP_FINGERS_MODE                        (NMP_FINGERS_MATCHER_BASE + 1000)
#define NMP_FINGERS_MIN_MATCHED_COUNT           (NMP_FINGERS_MATCHER_BASE + 1201)
#define NMP_FINGERS_MIN_MATCHED_COUNT_THRESHOLD (NMP_FINGERS_MATCHER_BASE + 1202)

#define NMP_FACES_MATCHER_BASE   11536
#define NMP_FACES_MATCHING_SPEED (NMP_FACES_MATCHER_BASE +    1)

#define NMP_IRISES_MATCHER_BASE                19536
#define NMP_IRISES_MATCHING_SPEED              (NMP_IRISES_MATCHER_BASE +    1)
#define NMP_IRISES_MAXIMAL_ROTATION            (NMP_IRISES_MATCHER_BASE +    2)
#define NMP_IRISES_MIN_MATCHED_COUNT           (NMP_IRISES_MATCHER_BASE + 1201)
#define NMP_IRISES_MIN_MATCHED_COUNT_THRESHOLD (NMP_IRISES_MATCHER_BASE + 1202)

#define NMP_PALMS_MATCHER_BASE                27536
#define NMP_PALMS_MAXIMAL_ROTATION            (NMP_PALMS_MATCHER_BASE +  201)
#define NMP_PALMS_MATCHING_SPEED              (NMP_PALMS_MATCHER_BASE +  220)
#define NMP_PALMS_FILL_FULL_MATCHING_DETAILS  (NMP_PALMS_MATCHER_BASE +  900)
#define NMP_PALMS_MIN_MATCHED_COUNT           (NMP_PALMS_MATCHER_BASE + 1201)
#define NMP_PALMS_MIN_MATCHED_COUNT_THRESHOLD (NMP_PALMS_MATCHER_BASE + 1202)

#define NMP_VOICES_MATCHER_BASE        35536
#define NMP_VOICES_UNIQUE_PHRASES_ONLY (NMP_VOICES_MATCHER_BASE +    2)

#define NM_FINGERS_MODE_GENERAL                       0
#define NM_FINGERS_MODE_DIGITALPERSONA_UAREU        100
#define NM_FINGERS_MODE_BIOMETRIKA_FX2000           200
#define NM_FINGERS_MODE_BIOMETRIKA_FX3000           201
#define NM_FINGERS_MODE_KEYTRONIC_SECUREDESKTOP     300
#define NM_FINGERS_MODE_IDENTIX_TOUCHVIEW           400
#define NM_FINGERS_MODE_IDENTIX_DFR2090             401
#define NM_FINGERS_MODE_PRECISEBIOMETRICS_100CS     500
#define NM_FINGERS_MODE_UPEK_TOUCHCHIP              600
#define NM_FINGERS_MODE_IDENTICATORTECHNOLOGY_DF90  700
#define NM_FINGERS_MODE_AUTHENTEC_AFS2              800
#define NM_FINGERS_MODE_AUTHENTEC_AES4000           810
#define NM_FINGERS_MODE_AUTHENTEC_AES2501B          811
#define NM_FINGERS_MODE_ATMEL_FINGERCHIP            900
#define NM_FINGERS_MODE_BMF_BLP100                 1000
#define NM_FINGERS_MODE_SECUGEN_HAMSTER            1100
#define NM_FINGERS_MODE_ETHENTICA                  1200
#define NM_FINGERS_MODE_CROSSMATCH_VERIFIER300     1300
#define NM_FINGERS_MODE_NITGEN_FINGKEY_HAMSTER     1400
#define NM_FINGERS_MODE_TESTECH_BIOI               1500
#define NM_FINGERS_MODE_DIGENT_IZZIX               1600
#define NM_FINGERS_MODE_STARTEK_FM200              1700
#define NM_FINGERS_MODE_FUJITSU_MBF200             1800
#define NM_FINGERS_MODE_FUTRONIC_FS80              1900
#define NM_FINGERS_MODE_LIGHTUNING_LTTC500         2000
#define NM_FINGERS_MODE_TACOMA_CMOS                2100

#ifdef N_CPP
}
#endif

#endif // !N_MATCHER_PARAMS_H_INCLUDED
