#ifndef NS_EXTRACTOR_PARAMS_H_INCLUDED
#define NS_EXTRACTOR_PARAMS_H_INCLUDED

#include <Core/NParameters.h>

#ifdef N_CPP
extern "C"
{
#endif

#define NSEP_MIN_PHRASE_DURATION   34036
#define NSEP_MAX_PHRASE_DURATION   34037

#define NSEP_EXTRACT_TEXT_DEPENDENT_FEATURES   34048
#define NSEP_EXTRACT_TEXT_INDEPENDENT_FEATURES 34049

#define NSEP_MAX_PAUSE_DURATION    35012
#define NSEP_USE_SPEAKER_DETECTION 35020

#ifdef N_CPP
}
#endif

#endif // !NS_EXTRACTOR_PARAMS_H_INCLUDED
